### PR TITLE
Fix some things that occurred to me

### PR DESCRIPTION
**Pull request by rmoehn**
Running lein-grim didn't work at all as advertised… If you want those commits separately, tell me. For now I thought making four pull requests would be tedious.

### CODE REVIEW

**Comment by rmoehn** [comment]
But detritus it's [`require`d](https://github.com/clojure-grimoire/lein-grim/blob/master/src/grimoire/doc.clj#L16). And at least `var->ns` is used transitively by `-main`. I haven't checked the other refers.

**Comment by arrdem** [comment]
Ok that is probably a bug then. I threw out the detritus require because I was depending on an old version for `deftag` and associated manipulations.

**Comment by arrdem** [comment]
Will drop a new release in a sec.

**Comment by rmoehn** [comment]
Wait a second, I will see if I can bump the version of lib-grimoire. Right now I'm having problems, because lib-grimoire 0.9.3 uses a version of guten-tag with `TagDescriptor`, but Leiningen puts on the classpath the version of guten-tag lib-grenada uses, which doesn't have a `TagDescriptor`.

**Pull request merged**
